Repository FossifyOrg/Launcher, pull requests merged in 2025-05, with the labels that each got.

#134 chore(l10n): update translations
  app/src/main/res/values-el/strings.xml
Labels: l10n

#145 docs: remove local pr template
  .github/PULL_REQUEST_TEMPLATE.md
Labels: documentation

#151 chore(l10n): remove invalid short description
  fastlane/metadata/android/ru-RU/short_description.txt
Labels: l10n

#153 ci: use fossifybot github app token
  .github/workflows/foss-release.yml
  .github/workflows/gplay-release.yml
  .github/workflows/image-minimizer.yml
  .github/workflows/no-response.yml
  .github/workflows/pr-labeler.yml
  .github/workflows/release-commenter.yml
Labels: ci

#157 ci(dependabot): add jitpack registry for gradle
  .github/dependabot.yml
Labels: ci
